---
- hosts: all
  become: yes

  vars:
    redis_name: ml-redis
    redis_image: redis
    redis_port: 6379
    api_name: ml-api
    api_image: ariel17/ml-st-1:api
    api_port: 8000
    plot_directory: /src/ml-st-1/plot
    web_name: ml-web
    web_image: ariel17/ml-st-1:web
    web_port: 9000

  tasks:
    - name: Creates Redis container
      docker:
        name: "{{ redis_name }}"
        image: "{{ redis_image }}"
        state: restarted
        pull: always
        restart_policy: always
        ports:
          - "{{ redis_port }}:6379"
      tags:
        - redis

    - name: Creates remote directory to store plotting
      file:
        path: "{{ plot_directory }}"
        state: directory
      tags:
        - api
    
    - name: Creates ML API container
      docker:
        name: "{{ api_name }}"
        image: "{{ api_image }}"
        state: restarted
        pull: always
        restart_policy: always
        env:
          REDIS_HOST: redis
          REDIS_PORT: "{{ redis_port }}"
        ports:
          - "{{ api_port }}:5000"
        links:
          - "{{ redis_name }}:redis"
        volumes:
          - "{{ plot_directory }}:/src/ml-st-1/src/plot"
      tags:
        - api

    - name: Creates ML Web container
      docker:
        name: "{{ api_name }}"
        image: "{{ api_image }}"
        state: restarted
        pull: always
        restart_policy: always
        ports:
          - "{{ web_port }}:80"
        links:
          - "{{ api_name }}:api"
        volumes_from:
          - "{{ api_name }}"
      tags:
        - web
