REDIS_HOST_KEY = 'REDIS_HOST'
REDIS_HOST_DEFAULT = 'localhost'

REDIS_PORT_KEY = 'REDIS_PORT'
REDIS_PORT_DEFAULT = 6379

REDIS_CONTEXT_KEY = 'REDIS_CONTEXT_KEY'
REDIS_CONTEXT_DEFAULT = 0

OPTIMAL_ACEPTABLE_ROUND_ERROR = 0.0002

DB_DAY_PREFIX = 'day-'
